### ISSUE TITLE
[something]: [something]

### ISSUE THREAD

**Issue by koviubi56** [koviubi56/chimdows#1]
# Bug report
## The bug
When I write this command: `SOMETHING: SOMETHING`, Chimdows is closed.
## Expected behavior
It says an error message `"SOMETHING: SOMETHING" command not exist.`
## Log
:START
[command

## Comment
Yes, it's made by the creator!

**Comment by kovcszaln6** [comment]
Update - We are not seeing any error messages, so we think the problem is with batch.

**Comment by koviubi56** [comment]
Update - We have an idea to disable users for using not letters.

**Comment by koviubi56** [comment]
_sad_ Update - We think this bug is by cmd, and it's not our problem.

**Comment by koviubi56** [comment]
# END
If you have an idea, write an email: `chimdows@hash.fyi` with subject: "Chimdows-Github: Issue-1: have idea"

***
